package com.persistence.login.bean;

public class DataClearVersionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_clear_version.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_clear_version.f_is_use
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private Integer isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_clear_version.f_update_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String updateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_clear_version.f_update_context
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String updateContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_clear_version.f_version
     *
     * @return the value of t_data_clear_version.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_clear_version.f_version
     *
     * @param version the value for t_data_clear_version.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_clear_version.f_is_use
     *
     * @return the value of t_data_clear_version.f_is_use
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_clear_version.f_is_use
     *
     * @param isUse the value for t_data_clear_version.f_is_use
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_clear_version.f_update_url
     *
     * @return the value of t_data_clear_version.f_update_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_clear_version.f_update_url
     *
     * @param updateUrl the value for t_data_clear_version.f_update_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_clear_version.f_update_context
     *
     * @return the value of t_data_clear_version.f_update_context
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getUpdateContext() {
        return updateContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_clear_version.f_update_context
     *
     * @param updateContext the value for t_data_clear_version.f_update_context
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setUpdateContext(String updateContext) {
        this.updateContext = updateContext;
    }
}