package com.persistence.login.bean;

public class DataPackEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_pack.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_pack.f_pre_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String preVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_pack.f_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_pack.f_size
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    private Float size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_pack.f_version
     *
     * @return the value of t_data_pack.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_pack.f_version
     *
     * @param version the value for t_data_pack.f_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_pack.f_pre_version
     *
     * @return the value of t_data_pack.f_pre_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getPreVersion() {
        return preVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_pack.f_pre_version
     *
     * @param preVersion the value for t_data_pack.f_pre_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setPreVersion(String preVersion) {
        this.preVersion = preVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_pack.f_url
     *
     * @return the value of t_data_pack.f_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_pack.f_url
     *
     * @param url the value for t_data_pack.f_url
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_pack.f_size
     *
     * @return the value of t_data_pack.f_size
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public Float getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_pack.f_size
     *
     * @param size the value for t_data_pack.f_size
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    public void setSize(Float size) {
        this.size = size;
    }
}