package com.persistence.login.bean;

public class FunctionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.f_url
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.f_show
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Boolean show;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.f_pid
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.f_id
     *
     * @return the value of t_function.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.f_id
     *
     * @param id the value for t_function.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.f_name
     *
     * @return the value of t_function.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.f_name
     *
     * @param name the value for t_function.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.f_url
     *
     * @return the value of t_function.f_url
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.f_url
     *
     * @param url the value for t_function.f_url
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.f_show
     *
     * @return the value of t_function.f_show
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Boolean getShow() {
        return show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.f_show
     *
     * @param show the value for t_function.f_show
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setShow(Boolean show) {
        this.show = show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_function.f_pid
     *
     * @return the value of t_function.f_pid
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_function.f_pid
     *
     * @param pid the value for t_function.f_pid
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}