package com.persistence.login.bean;

public class RoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.f_pids
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String pids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.f_funs
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String funs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.f_stars
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String stars;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.f_id
     *
     * @return the value of t_role.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.f_id
     *
     * @param id the value for t_role.f_id
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.f_name
     *
     * @return the value of t_role.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.f_name
     *
     * @param name the value for t_role.f_name
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.f_pids
     *
     * @return the value of t_role.f_pids
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getPids() {
        return pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.f_pids
     *
     * @param pids the value for t_role.f_pids
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setPids(String pids) {
        this.pids = pids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.f_funs
     *
     * @return the value of t_role.f_funs
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getFuns() {
        return funs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.f_funs
     *
     * @param funs the value for t_role.f_funs
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setFuns(String funs) {
        this.funs = funs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.f_stars
     *
     * @return the value of t_role.f_stars
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.f_stars
     *
     * @param stars the value for t_role.f_stars
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setStars(String stars) {
        this.stars = stars;
    }
}