package com.persistence.login.bean;

public class ServerEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_id
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_name
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_url
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_time
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_is_open
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private Integer isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_state
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server.f_version
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_id
     *
     * @return the value of t_server.f_id
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_id
     *
     * @param id the value for t_server.f_id
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_name
     *
     * @return the value of t_server.f_name
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_name
     *
     * @param name the value for t_server.f_name
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_url
     *
     * @return the value of t_server.f_url
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_url
     *
     * @param url the value for t_server.f_url
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_time
     *
     * @return the value of t_server.f_time
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_time
     *
     * @param time the value for t_server.f_time
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_is_open
     *
     * @return the value of t_server.f_is_open
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_is_open
     *
     * @param isOpen the value for t_server.f_is_open
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_state
     *
     * @return the value of t_server.f_state
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_state
     *
     * @param state the value for t_server.f_state
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server.f_version
     *
     * @return the value of t_server.f_version
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server.f_version
     *
     * @param version the value for t_server.f_version
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }
}