package com.persistence.login.bean;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_user
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_createtime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_lastloginip
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_password
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_lastlogintime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Long lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_lastedittime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    private Long lastedittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_user
     *
     * @return the value of t_user.f_user
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_user
     *
     * @param user the value for t_user.f_user
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_role
     *
     * @return the value of t_user.f_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_role
     *
     * @param role the value for t_user.f_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_createtime
     *
     * @return the value of t_user.f_createtime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_createtime
     *
     * @param createtime the value for t_user.f_createtime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_lastloginip
     *
     * @return the value of t_user.f_lastloginip
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_lastloginip
     *
     * @param lastloginip the value for t_user.f_lastloginip
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_password
     *
     * @return the value of t_user.f_password
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_password
     *
     * @param password the value for t_user.f_password
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_lastlogintime
     *
     * @return the value of t_user.f_lastlogintime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Long getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_lastlogintime
     *
     * @param lastlogintime the value for t_user.f_lastlogintime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setLastlogintime(Long lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_lastedittime
     *
     * @return the value of t_user.f_lastedittime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public Long getLastedittime() {
        return lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_lastedittime
     *
     * @param lastedittime the value for t_user.f_lastedittime
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    public void setLastedittime(Long lastedittime) {
        this.lastedittime = lastedittime;
    }
}