package com.persistence.login.mapp;

import com.persistence.login.bean.DataClearVersionEntity;
import com.persistence.login.bean.DataClearVersionEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataClearVersionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int countByExample(DataClearVersionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int deleteByExample(DataClearVersionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int insert(DataClearVersionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int insertSelective(DataClearVersionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    List<DataClearVersionEntity> selectByExample(DataClearVersionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    DataClearVersionEntity selectByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") DataClearVersionEntity record, @Param("example") DataClearVersionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByExample(@Param("record") DataClearVersionEntity record, @Param("example") DataClearVersionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(DataClearVersionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_clear_version
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByPrimaryKey(DataClearVersionEntity record);
}