package com.persistence.login.mapp;

import com.persistence.login.bean.DataPackEntity;
import com.persistence.login.bean.DataPackEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataPackEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int countByExample(DataPackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int deleteByExample(DataPackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int insert(DataPackEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int insertSelective(DataPackEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    List<DataPackEntity> selectByExample(DataPackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    DataPackEntity selectByPrimaryKey(String version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") DataPackEntity record, @Param("example") DataPackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByExample(@Param("record") DataPackEntity record, @Param("example") DataPackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(DataPackEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_pack
     *
     * @mbggenerated Wed Aug 05 14:20:00 GMT+08:00 2015
     */
    int updateByPrimaryKey(DataPackEntity record);
}