package com.persistence.login.mapp;

import com.persistence.login.bean.FunctionEntity;
import com.persistence.login.bean.FunctionEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FunctionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int countByExample(FunctionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int deleteByExample(FunctionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int insert(FunctionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int insertSelective(FunctionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    List<FunctionEntity> selectByExample(FunctionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    FunctionEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FunctionEntity record, @Param("example") FunctionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FunctionEntity record, @Param("example") FunctionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FunctionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByPrimaryKey(FunctionEntity record);
}