package com.persistence.login.mapp;

import com.persistence.login.bean.RoleEntity;
import com.persistence.login.bean.RoleEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int countByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int deleteByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    List<RoleEntity> selectByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    RoleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByExample(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Thu Aug 06 10:41:33 GMT+08:00 2015
     */
    int updateByPrimaryKey(RoleEntity record);
}