package com.persistence.login.mapp;

import com.persistence.login.bean.ServerEntity;
import com.persistence.login.bean.ServerEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int countByExample(ServerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int deleteByExample(ServerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int insert(ServerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int insertSelective(ServerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    List<ServerEntity> selectByExample(ServerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    ServerEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ServerEntity record, @Param("example") ServerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ServerEntity record, @Param("example") ServerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ServerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server
     *
     * @mbggenerated Wed Aug 12 11:10:01 GMT+08:00 2015
     */
    int updateByPrimaryKey(ServerEntity record);
}